seed: 42
deterministic: true

# Model to instantiate via timm
model: vit_base_patch16_224
num_classes: 2
pretrained: true

# Data module params
batch_size: 32
num_workers: 4
val_split: 0.1
test_split: 0.1
robustness_split: 0.1

# IMPORTANT: don't load a finetuned checkpoint
checkpoint_path: runs/crack_detection-vit_base_patch16_head_4/vit_base_patch16_224-epoch=00-val_loss=0.2208.ckpt

# Output
output_dir: reports/eval_trained_resnet
save_predictions: true
save_confusion_matrix: true

# Optional MLflow logging
use_mlflow: false
tracking_uri: file:./mlruns
experiment_name: crack_detection
run_name: eval_trained_vit




