seed: 42
deterministic: true

# Model to instantiate via timm
model: resnet50
num_classes: 2
pretrained: true

# Data module params
batch_size: 1
num_workers: 4
val_split: 0.1
test_split: 0.1
robustness_split: 0.1

# IMPORTANT: don't load a finetuned checkpoint
checkpoint_path: 1/b91702df9a7045dcba7f5b42444b4ee3/checkpoints/resnet50-epoch=03-val_loss=0.6399.ckpt

# Output
output_dir: reports/eval_trained_resnet
save_predictions: true
save_confusion_matrix: true

# Optional MLflow logging
use_mlflow: false
tracking_uri: file:./mlruns
experiment_name: crack_detection
run_name: eval_pretrained_resnet

# Explainability output
n_explain_images: 4
overlay_alpha: 0.45

# SHAP controls
do_shap: true
shap_n_segments: 40
shap_compactness: 10.0
shap_nsamples: 80
shap_baseline: blur


# ViT patch SHAP (VERY slow)
do_shap_vit_patch: false
vit_patch_size: 16
vit_patch_shap_nsamples: 5
vit_patch_shap_baseline: blur