seed: 42
deterministic: true

# Model to instantiate via timm
model: vit_base_patch16_224
num_classes: 2
pretrained: true

# Data module params
batch_size: 1
num_workers: 4
val_split: 0.1
test_split: 0.1
robustness_split: 0.1

checkpoint_path: runs/crack_detection-vit_base_patch16_head_4/vit_base_patch16_224-epoch=00-val_loss=0.2208.ckpt

# Output
output_dir: reports/eval_trained_vit
save_predictions: true
save_confusion_matrix: true

# Optional MLflow logging
use_mlflow: false
tracking_uri: file:./mlruns
experiment_name: crack_detection
run_name: eval_pretrained_resnet

# Explainability output
n_explain_images: 4
overlay_alpha: 0.45

# SHAP controls
do_shap: true
do_shap_vit_patch: false
vit_patch_shap_nsamples: 80

vit_patch_size: 16
vit_patch_shap_nsamples: 2
vit_patch_shap_baseline: blur