model: resnet50
pretrained: true
num_classes: 2
optimizer: adam
learning_rate: 0.000001
weight_decay: 0.0001
# scheduler: cosine
batch_size: 32
epochs: 30
num_workers: 4
val_split: 0.1
test_split: 0.1
robustness_split: 0.1
freeze_backbone: true
experiment_name: "crack_detection"
tracking_uri: "sqlite:///mlflow.db"
run_name: resnet50_head_2
deterministic: true